version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: cond_way
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d

  app:
    image: cond-way-api
    container_name: app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/cond_way
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      EMAIL_PASS: '#Gmm&mNu0t##0Ya'
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data: