version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 612415Lc@*
      MYSQL_ROOT_PASSWORD: 612415Lc@*
      MYSQL_DATABASE: cond_way
    ports:
      - "3306:3306"
    networks:
      - dev-network
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: /Users/lucascampolina/workspace/cond-way
#    image: cond-way-app
    container_name: cond-way-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/cond-way
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 612415Lc@*
    depends_on:
      - mysql
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  mysql-data:

